/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DatabaseCreateNestedManyWithoutFilesInput } from "./DatabaseCreateNestedManyWithoutFilesInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { DataEnrichmentCreateNestedManyWithoutFilesInput } from "./DataEnrichmentCreateNestedManyWithoutFilesInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumFileStatus } from "./EnumFileStatus";

@InputType()
class FileCreateInput {
  @ApiProperty({
    required: false,
    type: () => DatabaseCreateNestedManyWithoutFilesInput,
  })
  @ValidateNested()
  @Type(() => DatabaseCreateNestedManyWithoutFilesInput)
  @IsOptional()
  @Field(() => DatabaseCreateNestedManyWithoutFilesInput, {
    nullable: true,
  })
  databases?: DatabaseCreateNestedManyWithoutFilesInput;

  @ApiProperty({
    required: false,
    type: () => DataEnrichmentCreateNestedManyWithoutFilesInput,
  })
  @ValidateNested()
  @Type(() => DataEnrichmentCreateNestedManyWithoutFilesInput)
  @IsOptional()
  @Field(() => DataEnrichmentCreateNestedManyWithoutFilesInput, {
    nullable: true,
  })
  dataEnrichments?: DataEnrichmentCreateNestedManyWithoutFilesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  filecontent?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  filename?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumFileStatus,
  })
  @IsEnum(EnumFileStatus)
  @IsOptional()
  @Field(() => EnumFileStatus, {
    nullable: true,
  })
  status?: "Option1" | null;
}

export { FileCreateInput as FileCreateInput };
